config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :questions
  resources :chapters
  namespace :admin do
    root to: "admin/chapters#index"
    resources :chapters
    resources :questions
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :questions
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
	belongs_to :questions
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < ApplicationController
	def index
		@chapter = Chapter.all
	end

	def new
		@chapter = Chapter.new
	end

	def create
		chapter = Chapter.new(chapter_params)
		chapter.save
		redirect_to admin_chapters_path
	end
	def edit
		@chapter = Chapter.find(params[:id])
	end
	def update
		@chapter = Chapter.find(params[:id])
		@chapter.update(chapter_params)
		redirect_to admin_chapters_path
	end
	def destroy
		@chapter = Chapter.find(params[:id])
		@chapter.destroy
		redirect_to admin_chapters_path
	end
	private
		def chapter_params
			params.require(:chapter).permit(:chapter)
		end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
	def index
		@question = Question.all
	end

	def new
		@question = Question.new
	end

	def create
		question = Question.new(question_params)
		question.save
		redirect_to admin_questions_path
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		@question.update(question_params)
		redirect_to admin_question_path
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		redirect_to admin_questions_path
	end

	def show
		@question = Question.find(params[:id])
	end

	private
		def question_params
			params.require(:question).permit(:question)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@question = Question.all
	end

end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/chapters/_form.html.haml
= form_for chapter do |f|
	= f.label :chapter, 'naam'
	= f.text_field :chapter

	= f.submit 'Opslaan'

app/views/admin/chapters/edit.html.haml
= render 'form', chapter: @chapter

app/views/admin/chapters/index.html.haml
.col-md-12
	%h1 Handboek voor leraren
	%h3 Overzicht hoofdstukken
= link_to 'hoofdstuk toevoegen', new_admin_chapter_path, class: 'btn btn-primary' 
.col-md-5
	.panel.panel-primary
		.panel-heading 
			Alle hoofdstukken
		%table.table.table-striped
			%tr
				%td ID
				%td Naam
				%td bewerken
				%td verwijderen
			- @chapter.each do |chapter|
				%tr
					%td= chapter.id
					%td= chapter.chapter
					%td= link_to 'Bewerken', edit_admin_chapter_path(chapter), class: 'btn btn-warning'
					%td= link_to 'Verwijderen', admin_chapter_path(chapter), method: :delete, data: {confirm: 'Zeker weten?'}, class: 'btn btn-danger'

app/views/admin/chapters/new.html.haml
= render 'form', chapter: @chapter

app/views/admin/questions/_form.html.haml
= form_for [:admin, question] do |f|
	= f.label :question, 'Vraag'
	= f.text_field :question

	= f.submit 'Opslaan'

app/views/admin/questions/edit.html.haml
= render 'form', question: @question

app/views/admin/questions/index.html.haml
%h1 Ask your questions here!

= link_to 'Nieuwe vraag', new_admin_question_path, class: 'btn btn-primary'
.panel.panel-default
	.panel-heading Alle vragen
	%table.table.table-striped
		%tr
			%td ID
			%td Vraag
			%td Details
			%td Edit
			%td Delete

		- @question.each do |question|
			%tr 
				%td= question.id
				%td= question.question
				%td= link_to 'Show', admin_question_path(question), class: 'btn btn-success'
				%td= link_to 'Wijzig', edit_admin_question_path(question), class: 'btn btn-warning'
				%td= link_to 'Verwijderen', admin_question_path(question), method: :delete, data:{confirm: "Weet je het zeker?"}, class: 'btn btn-danger'

app/views/admin/questions/show.html.haml
%table.table
	%tr
		%td= @question.id
	%tr
		%td= @question.question
	%tr
		%td= @question.created_at
	%tr
		%td= @question.updated_at
	%tr
		%td= link_to 'Overzicht', admin_questions_path, class: 'btn btn-success'
	%tr
		%td= link_to 'Wijzig', edit_admin_question_path, class: 'btn btn-warning'
	%tr
		%td= link_to 'Verwijderen', admin_question_path, method: :delete, data:{confirm: "Weet je het zeker?"}, class: 'btn btn-danger'

app/views/layouts/1application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Leraren Quiz

		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true

    
		= csrf_meta_tags
  
	%body
		#menu
			%ul
				%li
					%a 
						= link_to 'Home', questions_url
				%li
					%a 
						= link_to 'Admin Vragen overzicht', admin_questions_url
		= yield

app/views/questions/index.html.haml
Welkom bij de Leraren Applicatie!

app/views/questions/new.html.haml
= render 'form', question: @question